name: tv_guide
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_secure_storage: ^9.2.2
  get_it: ^7.7.0
  go_router: ^14.2.1
  google_fonts: ^6.2.1
  heroicons_flutter: ^0.3.0
  loading_animation_widget: ^1.2.1
  meta: ^1.12.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo_no_bg.png'
